import React, { useEffect, useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import MapView, { Marker, MapPressEvent, Region } from 'react-native-maps';
import * as Location from 'expo-location';
import { router } from 'expo-router';
import { requestApi, useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { PrimaryButton, Screen } from '@/components/SmartServeUI';

type Picked = { latitude:number; longitude:number; formattedAddress?:string; area?:string; city?:string; state?:string; postalCode?:string; country?:string };
export default function LocationScreen(){ const colors=useColors(); const {token,role,setLocationLabel}=useApp(); const [region,setRegion]=useState<Region|null>(null); const [picked,setPicked]=useState<Picked|null>(null); const [query,setQuery]=useState(''); const [busy,setBusy]=useState(false); const [radius,setRadius]=useState('10');
 useEffect(()=>{ if(token) void requestApi<any>(role==='provider'?'/provider/location':'/customer/location',{},token).then(d=>{const l=d.location;if(l){const p={...l,latitude:Number(l.latitude),longitude:Number(l.longitude)};setPicked(p);setRegion({...p,latitudeDelta:.04,longitudeDelta:.04});setRadius(l.serviceRadiusKm||'10');}}).catch(()=>undefined); },[token,role]);
 const enrich=async(latitude:number,longitude:number)=>{setBusy(true);try{const [a]=await Location.reverseGeocodeAsync({latitude,longitude}); const p={latitude,longitude,formattedAddress:[a?.name,a?.street,a?.district].filter(Boolean).join(', ')||undefined,area:a?.district||a?.subregion||undefined,city:a?.city||a?.subregion||undefined,state:a?.region||undefined,postalCode:a?.postalCode||undefined,country:a?.country||undefined};setPicked(p);setRegion({...p,latitudeDelta:.04,longitudeDelta:.04});}catch{setPicked({latitude,longitude});}finally{setBusy(false);}};
 const current=async()=>{setBusy(true);try{const perm=await Location.requestForegroundPermissionsAsync();if(!perm.granted){Alert.alert('Location permission needed','Choose a point on the map or try again.');return;}const l=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});await enrich(l.coords.latitude,l.coords.longitude);}catch{Alert.alert('Unable to determine location','Choose a location manually.');}finally{setBusy(false);}};
 const search=async()=>{if(!query.trim())return;setBusy(true);try{const r=await Location.geocodeAsync(query.trim());if(!r[0]){Alert.alert('Location not found','Try a broader area or address.');return;}await enrich(r[0].latitude,r[0].longitude);}catch{Alert.alert('Search unavailable','Try selecting a point on the map.');}finally{setBusy(false);}};
 const confirm=async()=>{console.log('[LOCATION DEBUG] confirm pressed');console.log('[LOCATION DEBUG] selectedLocation:',picked);if(!picked||!token||!Number.isFinite(Number(picked.latitude))||!Number.isFinite(Number(picked.longitude))){console.log('[LOCATION DEBUG] invalid selected coordinates',picked?.latitude,picked?.longitude);Alert.alert('Location required','Select a valid location before confirming.');return;}const payload={latitude:Number(picked.latitude),longitude:Number(picked.longitude),formattedAddress:picked.formattedAddress,address:picked.formattedAddress,area:picked.area,city:picked.city,state:picked.state,postalCode:picked.postalCode,...(role==='provider'?{serviceRadiusKm:radius}:{})};console.log('[LOCATION DEBUG] latitude:',payload.latitude,'longitude:',payload.longitude,'formatted address:',payload.formattedAddress,'city:',payload.city,'state:',payload.state,'postal code:',payload.postalCode);console.log('[LOCATION DEBUG] PUT /api/customer/location payload:',payload);console.log('[LOCATION DEBUG] latitude type:',typeof payload.latitude,'longitude type:',typeof payload.longitude);setBusy(true);try{const result=await requestApi<any>(role==='provider'?'/provider/location':'/customer/location',{method:'PUT',body:JSON.stringify(payload)},token);console.log('[LOCATION DEBUG] PUT response:',result);if(role==='customer'){const saved=await requestApi<any>('/customer/location',{},token);console.log('[LOCATION DEBUG] GET /api/customer/location response:',saved);}setLocationLabel(picked.area||picked.city||picked.formattedAddress||'Selected location');router.back();}catch(e){console.error('[LOCATION DEBUG] save failed',e);Alert.alert('Unable to save location',e instanceof Error?e.message:'Please try again.');}finally{setBusy(false);}};
 return <Screen><View style={styles.top}><Pressable onPress={()=>router.back()}><Text style={{color:colors.primary,fontSize:22}}>‹</Text></Pressable><Text style={[styles.title,{color:colors.foreground}]}>Select Location</Text></View><View style={styles.search}><TextInput value={query} onChangeText={setQuery} onSubmitEditing={search} placeholder="Search area, locality or address" placeholderTextColor={colors.mutedForeground} style={[styles.input,{color:colors.foreground}]}/><Pressable onPress={search}><Text style={{color:colors.primary,fontFamily:'Inter_600SemiBold'}}>Search</Text></Pressable></View>{region?<MapView style={styles.map} region={region} onPress={(e:MapPressEvent)=>enrich(e.nativeEvent.coordinate.latitude,e.nativeEvent.coordinate.longitude)} showsUserLocation><Marker coordinate={{latitude:picked?.latitude||region.latitude,longitude:picked?.longitude||region.longitude}}/></MapView>:<View style={[styles.mapEmpty,{backgroundColor:colors.secondary}]}><Text style={{color:colors.mutedForeground}}>Use your current location or search for an address.</Text></View>}<Pressable onPress={current} style={[styles.current,{borderColor:colors.primary}]}><Text style={{color:colors.primary,fontFamily:'Inter_600SemiBold'}}>{busy?'Finding location…':'Use Current Location'}</Text></Pressable>{picked&&<View style={[styles.details,{backgroundColor:colors.card,borderColor:colors.border}]}><Text style={{color:colors.foreground,fontFamily:'Inter_600SemiBold'}}>{picked.formattedAddress||'Selected coordinates'}</Text><Text style={{color:colors.mutedForeground}}>Lat {picked.latitude.toFixed(6)} · Lon {picked.longitude.toFixed(6)}</Text>{role==='provider'&&<TextInput value={radius} onChangeText={setRadius} keyboardType="decimal-pad" placeholder="Service radius in km" placeholderTextColor={colors.mutedForeground} style={[styles.radius,{color:colors.foreground,borderColor:colors.border}]}/>}</View>}<PrimaryButton onPress={confirm} icon="check">Confirm Location</PrimaryButton></Screen>}
const styles=StyleSheet.create({top:{flexDirection:'row',alignItems:'center',gap:12},title:{fontFamily:'Inter_700Bold',fontSize:22},search:{flexDirection:'row',alignItems:'center',gap:8},input:{flex:1,borderWidth:1,borderColor:'#34445a',borderRadius:14,paddingHorizontal:12,minHeight:48,fontFamily:'Inter_400Regular'},map:{height:300,borderRadius:18},mapEmpty:{height:300,borderRadius:18,alignItems:'center',justifyContent:'center',padding:24},current:{borderWidth:1,borderRadius:14,minHeight:48,alignItems:'center',justifyContent:'center'},details:{borderWidth:1,borderRadius:16,padding:14,gap:8},radius:{borderWidth:1,borderRadius:12,minHeight:42,paddingHorizontal:10}});
