import React, { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { requestApi, useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';
import { PrimaryButton, Screen } from '@/components/SmartServeUI';
export default function ProviderOnboarding() { const colors=useColors(); const {token}=useApp(); const [services,setServices]=useState<any[]>([]); const [selected,setSelected]=useState<string>(''); const [skill,setSkill]=useState(''); const [experience,setExperience]=useState(''); const [area,setArea]=useState('');
 useEffect(()=>{ if(token) void requestApi<any>('/services',{},token).then(d=>setServices(d.services??[])).catch(()=>undefined); },[token]);
 const save=async()=>{ if(!token||!selected){Alert.alert('Choose a service','Select your primary service to continue.');return;} try { await requestApi('/provider/services',{method:'PUT',body:JSON.stringify({services:[{serviceId:selected,skill}]})},token); await requestApi('/provider/profile',{method:'PUT',body:JSON.stringify({experienceYears:experience,serviceArea:area})},token); router.replace('/'); } catch(e){Alert.alert('Unable to save profile',e instanceof Error?e.message:'Please try again.');} };
 return <Screen><ScrollView contentContainerStyle={{gap:14,paddingBottom:24}}><Text style={[styles.brand,{color:colors.primary}]}>PROVIDER CONSOLE</Text><Text style={[styles.title,{color:colors.foreground}]}>Set up your services</Text><Text style={[styles.copy,{color:colors.mutedForeground}]}>Choose what you offer so customers can find you. Verification remains pending until reviewed.</Text><Text style={[styles.label,{color:colors.foreground}]}>Primary service</Text><View style={styles.grid}>{services.map(s=><Pressable key={s.id} onPress={()=>setSelected(s.id)} style={[styles.chip,{borderColor:selected===s.id?colors.primary:colors.border,backgroundColor:selected===s.id?colors.secondary:colors.card}]}><Text style={{color:colors.foreground}}>{s.name}</Text></Pressable>)}</View><TextInput placeholder="Skills (e.g. leak repair)" placeholderTextColor={colors.mutedForeground} value={skill} onChangeText={setSkill} style={[styles.input,{color:colors.foreground,borderColor:colors.border}]} /><TextInput placeholder="Years of experience" placeholderTextColor={colors.mutedForeground} value={experience} onChangeText={setExperience} keyboardType="numeric" style={[styles.input,{color:colors.foreground,borderColor:colors.border}]} /><TextInput placeholder="Service area / city" placeholderTextColor={colors.mutedForeground} value={area} onChangeText={setArea} style={[styles.input,{color:colors.foreground,borderColor:colors.border}]} /><PrimaryButton onPress={save} icon="check">Save provider profile</PrimaryButton></ScrollView></Screen> }
const styles=StyleSheet.create({brand:{fontFamily:'Inter_700Bold',letterSpacing:2,fontSize:12},title:{fontFamily:'Inter_700Bold',fontSize:28},copy:{fontFamily:'Inter_400Regular',lineHeight:20},label:{fontFamily:'Inter_600SemiBold',fontSize:14},grid:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{padding:12,borderRadius:14,borderWidth:1},input:{borderWidth:1,borderRadius:14,minHeight:50,paddingHorizontal:14,fontFamily:'Inter_400Regular'}});
