import { Router } from "express";
import { and, desc, eq, gte, lt, sql } from "drizzle-orm";
import { bookings, bookingLocationUpdates, customerLocations, customers, db, providerAvailability, providerLocations, providerProfiles, providerServices, providers, services, users } from "@workspace/db";
import { createSession, hashPassword, normalizeEmail, revokeSession, toPublicUser, validateLogin, validateSignup, verifyPassword } from "../lib/auth";
import { requireAuth, requireRole } from "../middlewares/auth";
const router = Router();
const validCoordinate = (value: unknown, min: number, max: number): boolean => { const n = typeof value === "number" ? value : typeof value === "string" && value.trim() !== "" ? Number(value) : NaN; return Number.isFinite(n) && n >= min && n <= max; };
const distanceKm = (aLat:number,aLon:number,bLat:number,bLon:number) => { const r=6371; const dLat=(bLat-aLat)*Math.PI/180; const dLon=(bLon-aLon)*Math.PI/180; const x=Math.sin(dLat/2)**2+Math.cos(aLat*Math.PI/180)*Math.cos(bLat*Math.PI/180)*Math.sin(dLon/2)**2; return r*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x)); };
router.post("/auth/signup", async (req, res, next): Promise<void> => { try {
  const input = validateSignup(req.body); const existing = await db.select({ id: users.id }).from(users).where(eq(users.email, input.email)).limit(1);
  if (existing[0]) { res.status(409).json({ message: "An account with this email already exists." }); return; }
  const passwordHash = await hashPassword(input.password);
  const user = await db.transaction(async (tx) => { const inserted = await tx.insert(users).values({ email: input.email, passwordHash, role: input.role }).returning(); const created = inserted[0]; if (!created) throw new Error("Could not create account."); if (input.role === "customer") await tx.insert(customers).values({ userId: created.id, displayName: input.displayName }); else { await tx.insert(providers).values({ userId: created.id, displayName: input.displayName }); await tx.insert(providerProfiles).values({ userId: created.id }); } return created; });
  res.status(201).json(await createSession(user));
} catch (error) { next(error); } });
router.post("/auth/login", async (req, res, next): Promise<void> => { try { const input = validateLogin(req.body); const user = (await db.select().from(users).where(eq(users.email, normalizeEmail(input.email))).limit(1))[0]; if (!user || !user.isActive || !(await verifyPassword(input.password, user.passwordHash))) { res.status(401).json({ message: "Invalid email or password." }); return; } res.json(await createSession(user)); } catch (error) { next(error); } });
router.post("/auth/logout", requireAuth, async (req, res, next): Promise<void> => { try { await revokeSession(req.authToken!); res.status(204).end(); } catch (error) { next(error); } });
router.get("/auth/me", requireAuth, async (req, res, next): Promise<void> => { try { res.json({ user: await toPublicUser(req.authUser!) }); } catch (error) { next(error); } });
router.get("/users/me", requireAuth, async (req, res, next): Promise<void> => { try { res.json({ user: await toPublicUser(req.authUser!) }); } catch (error) { next(error); } });

router.put("/customer/profile", requireAuth, requireRole("customer"), async (req,res,next):Promise<void>=>{try{const name=typeof req.body?.displayName==="string"?req.body.displayName.trim():"";if(name.length<2||name.length>120){res.status(422).json({message:"Display name must be between 2 and 120 characters."});return;}const [updated]=await db.update(customers).set({displayName:name,updatedAt:new Date()}).where(eq(customers.userId,req.authUser!.id)).returning();if(!updated){res.status(404).json({message:"Customer profile not found."});return;}res.json({user:await toPublicUser(req.authUser!)});}catch(e){next(e);}});
router.get("/services", async (_req, res, next): Promise<void> => { try { res.json({ services: await db.select().from(services).where(eq(services.status, "active")) }); } catch (error) { next(error); } });
router.get("/providers", requireAuth, requireRole("customer"), async (req, res, next): Promise<void> => { try { const slug = typeof req.query.service === "string" ? req.query.service : ""; if (!slug) { res.status(400).json({ message: "service is required." }); return; } const loc=(await db.select().from(customerLocations).where(and(eq(customerLocations.userId, req.authUser!.id), eq(customerLocations.isDefault, true))).limit(1))[0]; const rows = await db.select({ id: users.id, name: providers.displayName, service: services.name, serviceId: services.id, available: providerAvailability.available, verificationStatus: providerProfiles.verificationStatus, providerLat: providerLocations.latitude, providerLon: providerLocations.longitude, radius: sql<string>`coalesce(${providerLocations.serviceRadiusKm}, ${providerProfiles.serviceRadiusKm}, '10')` }).from(providerServices).innerJoin(users, eq(providerServices.providerId, users.id)).innerJoin(providers, eq(providers.userId, users.id)).innerJoin(services, eq(providerServices.serviceId, services.id)).innerJoin(providerAvailability, eq(providerAvailability.providerId, users.id)).leftJoin(providerProfiles, eq(providerProfiles.userId, users.id)).leftJoin(providerLocations, eq(providerLocations.providerId, users.id)).where(and(eq(services.slug, slug), eq(users.role, "provider"), eq(users.isActive, true), eq(providerAvailability.available, true))); const providersOut=rows.map((x:any)=>{ const has=loc&&validCoordinate(loc.latitude,-90,90)&&validCoordinate(loc.longitude,-180,180)&&validCoordinate(x.providerLat,-90,90)&&validCoordinate(x.providerLon,-180,180); const distance=has?distanceKm(Number(loc.latitude),Number(loc.longitude),Number(x.providerLat),Number(x.providerLon)):null; const radius=Number(x.radius||10); return {...x, distanceKm:distance===null?null:Number(distance.toFixed(2)), withinRadius:distance===null?false:distance<=radius}; }).filter((x:any)=>x.withinRadius); res.json({ providers: providersOut, locationRequired: !loc }); } catch (error) { next(error); } });
router.get("/providers/:id", requireAuth, requireRole("customer"), async (req, res, next): Promise<void> => { try {
  const providerId = String(req.params.id);
  const [row] = await db.select({ id: users.id, name: providers.displayName, email: users.email, available: providerAvailability.available, verificationStatus: providerProfiles.verificationStatus, experienceYears: providerProfiles.experienceYears, serviceArea: providerProfiles.serviceArea, city: providerProfiles.city, startingPrice: providerProfiles.startingPrice }).from(users).innerJoin(providers, eq(providers.userId, users.id)).leftJoin(providerProfiles, eq(providerProfiles.userId, users.id)).leftJoin(providerAvailability, eq(providerAvailability.providerId, users.id)).where(and(eq(users.id, providerId), eq(users.role, "provider"), eq(users.isActive, true))).limit(1);
  if (!row) { res.status(404).json({ message: "Provider not found." }); return; }
  const skills = await db.select({ id: services.id, name: services.name, slug: services.slug, skill: providerServices.skill }).from(providerServices).innerJoin(services, eq(providerServices.serviceId, services.id)).where(eq(providerServices.providerId, providerId));
  res.json({ provider: { ...row, skills } });
} catch (error) { next(error); } });
router.get("/provider/dashboard", requireAuth, requireRole("provider"), async (req, res, next): Promise<void> => { try {
  const providerId = req.authUser!.id;
  const now = new Date(); const currentStart = new Date(now.getFullYear(), now.getMonth(), 1); const previousStart = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const [availability, profile, completed, previous, recent, requests] = await Promise.all([
    db.select().from(providerAvailability).where(eq(providerAvailability.providerId, providerId)).limit(1),
    db.select().from(providerProfiles).where(eq(providerProfiles.userId, providerId)).limit(1),
    db.select({ jobs: sql<number>`count(*)::int`, amount: sql<string>`coalesce(sum(nullif(coalesce(${bookings.finalAmount}, ${bookings.amount}), '')::numeric), 0)::text` }).from(bookings).where(and(eq(bookings.providerId, providerId), eq(bookings.status, "completed"), gte(bookings.createdAt, currentStart))),
    db.select({ amount: sql<string>`coalesce(sum(nullif(coalesce(${bookings.finalAmount}, ${bookings.amount}), '')::numeric), 0)::text` }).from(bookings).where(and(eq(bookings.providerId, providerId), eq(bookings.status, "completed"), gte(bookings.createdAt, previousStart), lt(bookings.createdAt, currentStart))),
    db.select({ id: bookings.id, status: bookings.status, amount: sql<string>`coalesce(${bookings.finalAmount}, ${bookings.amount})`, createdAt: bookings.createdAt, service: services.name }).from(bookings).innerJoin(services, eq(bookings.serviceId, services.id)).where(eq(bookings.providerId, providerId)).orderBy(desc(bookings.createdAt)).limit(10),
    db.select({ id: bookings.id, status: bookings.status, amount: sql<string>`coalesce(${bookings.finalAmount}, ${bookings.amount})`, createdAt: bookings.createdAt, service: services.name }).from(bookings).innerJoin(services, eq(bookings.serviceId, services.id)).where(and(eq(bookings.providerId, providerId), eq(bookings.status, "requested"))).orderBy(desc(bookings.createdAt)).limit(5),
  ]);
  const completedRow = completed[0] ?? { jobs: 0, amount: "0" }; const previousRow = previous[0] ?? { amount: "0" }; const p = profile[0];
  res.json({ availability: availability[0]?.available ?? false, verificationStatus: p?.verificationStatus ?? "pending", earningsThisMonth: completedRow.amount, earningsPreviousMonth: previousRow.amount, completedJobs: completedRow.jobs, pendingAmount: "0", rating: null, onTimeRate: null, trustScore: null, recentJobs: recent, requests });
} catch (error) { next(error); } });
router.get("/provider/profile", requireAuth, requireRole("provider"), async (req, res, next): Promise<void> => { try { const profile = (await db.select().from(providerProfiles).where(eq(providerProfiles.userId, req.authUser!.id)).limit(1))[0] ?? null; const skills = await db.select({ id: services.id, name: services.name, slug: services.slug, skill: providerServices.skill }).from(providerServices).innerJoin(services, eq(providerServices.serviceId, services.id)).where(eq(providerServices.providerId, req.authUser!.id)); res.json({ user: await toPublicUser(req.authUser!), profile, skills }); } catch (error) { next(error); } });
router.put("/provider/services", requireAuth, requireRole("provider"), async (req, res, next): Promise<void> => { try { const items = Array.isArray(req.body?.services) ? req.body.services : []; if (!items.length || items.some((item: any) => typeof item?.serviceId !== "string")) { res.status(422).json({ message: "At least one serviceId is required." }); return; } await db.delete(providerServices).where(eq(providerServices.providerId, req.authUser!.id)); const rows = await db.insert(providerServices).values(items.map((item: any) => ({ providerId: req.authUser!.id, serviceId: item.serviceId, skill: typeof item.skill === "string" ? item.skill.trim() : null }))).returning(); res.json({ services: rows }); } catch (error) { next(error); } });
router.put("/provider/profile", requireAuth, requireRole("provider"), async (req, res, next): Promise<void> => { try { const body = req.body ?? {}; const row = await db.insert(providerProfiles).values({ userId: req.authUser!.id, phone: typeof body.phone === "string" ? body.phone.trim() : null, experienceYears: typeof body.experienceYears === "string" ? body.experienceYears.trim() : null, serviceArea: typeof body.serviceArea === "string" ? body.serviceArea.trim() : null, serviceRadiusKm: typeof body.serviceRadiusKm === "string" && Number(body.serviceRadiusKm) > 0 && Number(body.serviceRadiusKm) <= 100 ? body.serviceRadiusKm : "10", city: typeof body.city === "string" ? body.city.trim() : null, pincode: typeof body.pincode === "string" ? body.pincode.trim() : null, startingPrice: typeof body.startingPrice === "string" ? body.startingPrice.trim() : null, emergencyAvailable: body.emergencyAvailable === true }).onConflictDoUpdate({ target: providerProfiles.userId, set: { phone: typeof body.phone === "string" ? body.phone.trim() : null, experienceYears: typeof body.experienceYears === "string" ? body.experienceYears.trim() : null, serviceArea: typeof body.serviceArea === "string" ? body.serviceArea.trim() : null, serviceRadiusKm: typeof body.serviceRadiusKm === "string" && Number(body.serviceRadiusKm) > 0 && Number(body.serviceRadiusKm) <= 100 ? body.serviceRadiusKm : "10", city: typeof body.city === "string" ? body.city.trim() : null, pincode: typeof body.pincode === "string" ? body.pincode.trim() : null, startingPrice: typeof body.startingPrice === "string" ? body.startingPrice.trim() : null, emergencyAvailable: body.emergencyAvailable === true, updatedAt: new Date() } }).returning(); res.json({ profile: row[0] }); } catch (error) { next(error); } });
router.put("/provider/availability", requireAuth, requireRole("provider"), async (req, res, next): Promise<void> => { try { if (typeof req.body?.available !== "boolean") { res.status(400).json({ message: "available must be boolean." }); return; } const row = await db.insert(providerAvailability).values({ providerId: req.authUser!.id, available: req.body.available }).onConflictDoUpdate({ target: providerAvailability.providerId, set: { available: req.body.available, updatedAt: new Date() } }).returning(); res.json({ available: row[0]?.available ?? req.body.available }); } catch (error) { next(error); } });

router.get("/customer/location", requireAuth, requireRole("customer"), async (req,res,next):Promise<void>=>{try{const [location]=await db.select().from(customerLocations).where(eq(customerLocations.userId,req.authUser!.id)).orderBy(desc(customerLocations.updatedAt)).limit(1);res.json({location:location??null});}catch(e){next(e);}});
router.put("/customer/location", requireAuth, requireRole("customer"), async (req,res,next):Promise<void>=>{try{const b=req.body??{};const latitudeValid=validCoordinate(b.latitude,-90,90);const longitudeValid=validCoordinate(b.longitude,-180,180);console.log("CUSTOMER LOCATION REQUEST:", { body: b, latitude: b.latitude, longitude: b.longitude, latitudeType: typeof b.latitude, longitudeType: typeof b.longitude, latitudeValid, longitudeValid, userId: req.authUser?.id });if(!latitudeValid||!longitudeValid){res.status(422).json({message:"Valid latitude and longitude are required."});return;}const latitude=String(Number(b.latitude));const longitude=String(Number(b.longitude));await db.update(customerLocations).set({isDefault:false,updatedAt:new Date()}).where(eq(customerLocations.userId,req.authUser!.id));const [location]=await db.insert(customerLocations).values({userId:req.authUser!.id,latitude,longitude,formattedAddress:typeof b.formattedAddress==='string'?b.formattedAddress.slice(0,500):null,area:b.area??null,city:b.city??null,state:b.state??null,postalCode:b.postalCode??null,country:b.country??null,label:b.label??null,isDefault:true}).returning();res.json({location});}catch(e){next(e);}});
router.get("/provider/location", requireAuth, requireRole("provider"), async (req,res,next):Promise<void>=>{try{const [location]=await db.select().from(providerLocations).where(eq(providerLocations.providerId,req.authUser!.id)).limit(1);res.json({location:location??null});}catch(e){next(e);}});
router.put("/provider/location", requireAuth, requireRole("provider"), async (req,res,next):Promise<void>=>{try{const b=req.body??{};if(!validCoordinate(b.latitude,-90,90)||!validCoordinate(b.longitude,-180,180)){res.status(422).json({message:"Valid latitude and longitude are required."});return;}const radius=Number(b.serviceRadiusKm??10);if(!Number.isFinite(radius)||radius<=0||radius>100){res.status(422).json({message:"serviceRadiusKm must be between 1 and 100."});return;}const [location]=await db.insert(providerLocations).values({providerId:req.authUser!.id,latitude:b.latitude,longitude:b.longitude,serviceRadiusKm:String(radius)}).onConflictDoUpdate({target:providerLocations.providerId,set:{latitude:b.latitude,longitude:b.longitude,serviceRadiusKm:String(radius),updatedAt:new Date()}}).returning();res.json({location});}catch(e){next(e);}});
router.post("/bookings", requireAuth, requireRole("customer"), async (req, res, next): Promise<void> => { try {
  const { serviceId, providerId, problemDescription, address, scheduledAt, estimatedPriceMin, estimatedPriceMax, latitude, longitude, locationAddress, locationArea, locationCity, locationState, locationPostalCode } = req.body ?? {};
  if (typeof serviceId !== "string" || typeof providerId !== "string") { res.status(422).json({ message: "serviceId and providerId are required." }); return; }
  if (!validCoordinate(latitude,-90,90)||!validCoordinate(longitude,-180,180)) { res.status(422).json({ message: "A valid service location is required." }); return; }
  const [provider] = await db.select({ id: users.id }).from(users).innerJoin(providerServices, eq(providerServices.providerId, users.id)).innerJoin(providerAvailability, eq(providerAvailability.providerId, users.id)).where(and(eq(users.id, providerId), eq(users.role, "provider"), eq(users.isActive, true), eq(providerServices.serviceId, serviceId), eq(providerAvailability.available, true))).limit(1);
  if (!provider) { res.status(409).json({ message: "Provider is unavailable for this service." }); return; }
  const [service] = await db.select({ id: services.id }).from(services).where(and(eq(services.id, serviceId), eq(services.status, "active"))).limit(1);
  if (!service) { res.status(404).json({ message: "Service not found." }); return; }
  const [created] = await db.insert(bookings).values({ customerId: req.authUser!.id, providerId, serviceId, problemDescription: typeof problemDescription === "string" ? problemDescription.trim() : null, address: typeof address === "string" ? address.trim() : (typeof locationAddress === "string" ? locationAddress.trim() : null), latitude, longitude, locationAddress: typeof locationAddress === "string" ? locationAddress.trim() : null, locationArea: typeof locationArea === "string" ? locationArea.trim() : null, locationCity: typeof locationCity === "string" ? locationCity.trim() : null, locationState: typeof locationState === "string" ? locationState.trim() : null, locationPostalCode: typeof locationPostalCode === "string" ? locationPostalCode.trim() : null, scheduledAt: typeof scheduledAt === "string" ? new Date(scheduledAt) : null, estimatedPriceMin: typeof estimatedPriceMin === "string" ? estimatedPriceMin : null, estimatedPriceMax: typeof estimatedPriceMax === "string" ? estimatedPriceMax : null, status: "requested" }).returning();
  res.status(201).json({ booking: created });
} catch (error) { next(error); } });
router.get("/provider/jobs", requireAuth, requireRole("provider"), async (req, res, next): Promise<void> => { try { const rows = await db.select({ id: bookings.id, status: bookings.status, problemDescription: bookings.problemDescription, address: bookings.address, scheduledAt: bookings.scheduledAt, amount: sql<string>`coalesce(${bookings.finalAmount}, ${bookings.amount})`, createdAt: bookings.createdAt, service: services.name }).from(bookings).innerJoin(services, eq(bookings.serviceId, services.id)).where(eq(bookings.providerId, req.authUser!.id)).orderBy(desc(bookings.createdAt)); res.json({ jobs: rows }); } catch (error) { next(error); } });
router.get("/bookings/:id", requireAuth, async (req, res, next): Promise<void> => { try { const [booking] = await db.select({ id: bookings.id, customerId: bookings.customerId, providerId: bookings.providerId, status: bookings.status, problemDescription: bookings.problemDescription, address: bookings.address, latitude: bookings.latitude, longitude: bookings.longitude, locationAddress: bookings.locationAddress, locationArea: bookings.locationArea, locationCity: bookings.locationCity, locationState: bookings.locationState, locationPostalCode: bookings.locationPostalCode, scheduledAt: bookings.scheduledAt, amount: bookings.amount, finalAmount: bookings.finalAmount, createdAt: bookings.createdAt, service: services.name }).from(bookings).innerJoin(services, eq(bookings.serviceId, services.id)).where(eq(bookings.id, String(req.params.id))).limit(1); if (!booking) { res.status(404).json({ message: "Booking not found." }); return; } if (booking.customerId !== req.authUser!.id && booking.providerId !== req.authUser!.id) { res.status(403).json({ message: "You are not authorized to view this booking." }); return; } res.json({ booking }); } catch (error) { next(error); } });
const transitions: Record<string, string[]> = { requested: ["accepted", "rejected", "cancelled"], accepted: ["in_progress", "cancelled"], in_progress: ["completed"] };
router.patch("/bookings/:id/status", requireAuth, async (req, res, next): Promise<void> => { try { const nextStatus = req.body?.status; if (!["accepted", "rejected", "cancelled", "in_progress", "completed"].includes(nextStatus)) { res.status(422).json({ message: "Invalid booking status." }); return; } const [booking] = await db.select().from(bookings).where(eq(bookings.id, String(req.params.id))).limit(1); if (!booking) { res.status(404).json({ message: "Booking not found." }); return; } const owns = booking.customerId === req.authUser!.id || booking.providerId === req.authUser!.id; if (!owns) { res.status(403).json({ message: "You are not authorized to update this booking." }); return; } if (!transitions[booking.status]?.includes(nextStatus)) { res.status(409).json({ message: `Cannot transition booking from ${booking.status} to ${nextStatus}.` }); return; } const providerAction = ["accepted", "rejected", "in_progress", "completed"].includes(nextStatus); if (providerAction && (req.authUser!.role !== "provider" || booking.providerId !== req.authUser!.id)) { res.status(403).json({ message: "Only the assigned provider can perform this action." }); return; } if (nextStatus === "cancelled" && req.authUser!.role !== "customer") { res.status(403).json({ message: "Only the customer can cancel this request." }); return; } const now = new Date(); const [updated] = await db.update(bookings).set({ status: nextStatus as any, updatedAt: now, acceptedAt: nextStatus === "accepted" ? now : booking.acceptedAt, startedAt: nextStatus === "in_progress" ? now : booking.startedAt, completedAt: nextStatus === "completed" ? now : booking.completedAt, cancelledAt: nextStatus === "cancelled" ? now : booking.cancelledAt, finalAmount: nextStatus === "completed" ? (typeof req.body.finalAmount === "string" ? req.body.finalAmount : booking.finalAmount) : booking.finalAmount }).where(eq(bookings.id, booking.id)).returning(); res.json({ booking: updated }); } catch (error) { next(error); } });
router.put("/bookings/:id/provider-location", requireAuth, requireRole("provider"), async (req,res,next):Promise<void>=>{try{const b=req.body??{};if(!validCoordinate(b.latitude,-90,90)||!validCoordinate(b.longitude,-180,180)){res.status(422).json({message:"Valid latitude and longitude are required."});return;}const [booking]=await db.select().from(bookings).where(eq(bookings.id,String(req.params.id))).limit(1);if(!booking||booking.providerId!==req.authUser!.id){res.status(403).json({message:"Booking access denied."});return;}if(!["accepted","in_progress"].includes(booking.status)){res.status(409).json({message:"Location sharing is only available for active bookings."});return;}const [update]=await db.insert(bookingLocationUpdates).values({bookingId:booking.id,providerId:req.authUser!.id,latitude:b.latitude,longitude:b.longitude}).onConflictDoUpdate({target:bookingLocationUpdates.bookingId,set:{latitude:b.latitude,longitude:b.longitude,updatedAt:new Date()}}).returning();res.json({location:update});}catch(e){next(e);}});
router.get("/bookings/:id/provider-location", requireAuth, async (req,res,next):Promise<void>=>{try{const [booking]=await db.select().from(bookings).where(eq(bookings.id,String(req.params.id))).limit(1);if(!booking){res.status(404).json({message:"Booking not found."});return;}if(booking.customerId!==req.authUser!.id&&booking.providerId!==req.authUser!.id){res.status(403).json({message:"Booking access denied."});return;}if(!["accepted","in_progress"].includes(booking.status)){res.json({location:null});return;}const [location]=await db.select().from(bookingLocationUpdates).where(eq(bookingLocationUpdates.bookingId,booking.id)).limit(1);res.json({location:location??null});}catch(e){next(e);}});
router.get("/customer/bookings", requireAuth, requireRole("customer"), async (req, res, next): Promise<void> => { try { const rows = await db.select({ id: bookings.id, status: bookings.status, amount: sql<string>`coalesce(${bookings.finalAmount}, ${bookings.amount})`, createdAt: bookings.createdAt, service: services.name }).from(bookings).innerJoin(services, eq(bookings.serviceId, services.id)).where(eq(bookings.customerId, req.authUser!.id)).orderBy(desc(bookings.createdAt)); res.json({ bookings: rows }); } catch (error) { next(error); } });
router.get("/protected/customer", requireAuth, requireRole("customer"), (_req, res) => { res.json({ ok: true }); });
router.get("/protected/provider", requireAuth, requireRole("provider"), (_req, res) => { res.json({ ok: true }); });
export default router;
