import express, { type Express, type NextFunction, type Request, type Response } from "express";
import cors from "cors";
import pinoHttp from "pino-http";
import router from "./routes";
import { logger } from "./lib/logger";
const app: Express = express();
app.disable("x-powered-by");
app.use(pinoHttp({ logger, serializers: { req(req) { return { id: req.id, method: req.method, url: req.url?.split("?")[0] }; }, res(res) { return { statusCode: res.statusCode }; } } }));
app.use(cors({ origin: process.env.CORS_ORIGIN?.split(",") ?? true, methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"], allowedHeaders: ["Authorization", "Content-Type"] }));
app.use(express.json({ limit: "1mb" }));
app.use("/api", router);
app.use((_req, res) => res.status(404).json({ message: "Route not found." }));
app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { logger.error({ error }, "Unhandled API error"); const message = error instanceof Error ? error.message : "Unexpected server error."; res.status(message.includes("must") || message.includes("valid") || message.includes("Choose") || message.includes("Display") ? 400 : 500).json({ message }); });
export default app;
